apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pv-claim
  namespace: namespace-tawazun
  labels:
    app: sql
    name: name

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi