apiVersion: v1
kind: Service
metadata:
  name: mydatasql
  namespace: namespace-tawazun
  labels:
    app: sql
    name: name
spec:
  type: ClusterIP
  ports:
    - name: sql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: sql